package demo.productdiscount;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductList implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String product;
   private java.lang.String productType;
   private int minNumberofUnit;
   private java.lang.String unitType;
   private int totalSaleValue;
   private java.lang.String viewType;
   private int totalNumberofBooking;
   private java.lang.String startDate;
   private java.lang.String endDate;
   private java.lang.Double reductionPercent;
   private int reductiononFlat;
   private java.lang.String car;
   private java.lang.String waiver;
   private int addonsDisount;
   private java.lang.String existingCustomer;

   private int inventoryThreshold;

   public ProductList()
   {
   }

   public java.lang.String getProduct()
   {
      return this.product;
   }

   public void setProduct(java.lang.String product)
   {
      this.product = product;
   }

   public java.lang.String getProductType()
   {
      return this.productType;
   }

   public void setProductType(java.lang.String productType)
   {
      this.productType = productType;
   }

   public int getMinNumberofUnit()
   {
      return this.minNumberofUnit;
   }

   public void setMinNumberofUnit(int minNumberofUnit)
   {
      this.minNumberofUnit = minNumberofUnit;
   }

   public java.lang.String getUnitType()
   {
      return this.unitType;
   }

   public void setUnitType(java.lang.String unitType)
   {
      this.unitType = unitType;
   }

   public int getTotalSaleValue()
   {
      return this.totalSaleValue;
   }

   public void setTotalSaleValue(int totalSaleValue)
   {
      this.totalSaleValue = totalSaleValue;
   }

   public java.lang.String getViewType()
   {
      return this.viewType;
   }

   public void setViewType(java.lang.String viewType)
   {
      this.viewType = viewType;
   }

   public int getTotalNumberofBooking()
   {
      return this.totalNumberofBooking;
   }

   public void setTotalNumberofBooking(int totalNumberofBooking)
   {
      this.totalNumberofBooking = totalNumberofBooking;
   }

   public java.lang.String getStartDate()
   {
      return this.startDate;
   }

   public void setStartDate(java.lang.String startDate)
   {
      this.startDate = startDate;
   }

   public java.lang.String getEndDate()
   {
      return this.endDate;
   }

   public void setEndDate(java.lang.String endDate)
   {
      this.endDate = endDate;
   }

   public java.lang.Double getReductionPercent()
   {
      return this.reductionPercent;
   }

   public void setReductionPercent(java.lang.Double reductionPercent)
   {
      this.reductionPercent = reductionPercent;
   }

   public int getReductiononFlat()
   {
      return this.reductiononFlat;
   }

   public void setReductiononFlat(int reductiononFlat)
   {
      this.reductiononFlat = reductiononFlat;
   }

   public java.lang.String getCar()
   {
      return this.car;
   }

   public void setCar(java.lang.String car)
   {
      this.car = car;
   }

   public java.lang.String getWaiver()
   {
      return this.waiver;
   }

   public void setWaiver(java.lang.String waiver)
   {
      this.waiver = waiver;
   }

   public int getAddonsDisount()
   {
      return this.addonsDisount;
   }

   public void setAddonsDisount(int addonsDisount)
   {
      this.addonsDisount = addonsDisount;
   }

   public java.lang.String getExistingCustomer()
   {
      return this.existingCustomer;
   }

   public void setExistingCustomer(java.lang.String existingCustomer)
   {
      this.existingCustomer = existingCustomer;
   }

   public int getInventoryThreshold()
   {
      return this.inventoryThreshold;
   }

   public void setInventoryThreshold(int inventoryThreshold)
   {
      this.inventoryThreshold = inventoryThreshold;
   }

   public ProductList(java.lang.String product, java.lang.String productType,
         int minNumberofUnit, java.lang.String unitType, int totalSaleValue,
         java.lang.String viewType, int totalNumberofBooking,
         java.lang.String startDate, java.lang.String endDate,
         java.lang.Double reductionPercent, int reductiononFlat,
         java.lang.String car, java.lang.String waiver, int addonsDisount,
         java.lang.String existingCustomer, int inventoryThreshold)
   {
      this.product = product;
      this.productType = productType;
      this.minNumberofUnit = minNumberofUnit;
      this.unitType = unitType;
      this.totalSaleValue = totalSaleValue;
      this.viewType = viewType;
      this.totalNumberofBooking = totalNumberofBooking;
      this.startDate = startDate;
      this.endDate = endDate;
      this.reductionPercent = reductionPercent;
      this.reductiononFlat = reductiononFlat;
      this.car = car;
      this.waiver = waiver;
      this.addonsDisount = addonsDisount;
      this.existingCustomer = existingCustomer;
      this.inventoryThreshold = inventoryThreshold;
   }

}