package demo.promotionalrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Promotion implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String promotionName;
   private java.lang.String products;
   private java.lang.String week;
   private java.lang.String type;
   private int totalnoofBooking;
   private java.util.Date startDate;
   private java.util.Date endDate;
   private int priceChange;

   private String schemeId;

   public Promotion()
   {
   }

   public java.lang.String getPromotionName()
   {
      return this.promotionName;
   }

   public void setPromotionName(java.lang.String promotionName)
   {
      this.promotionName = promotionName;
   }

   public java.lang.String getProducts()
   {
      return this.products;
   }

   public void setProducts(java.lang.String products)
   {
      this.products = products;
   }

   public java.lang.String getWeek()
   {
      return this.week;
   }

   public void setWeek(java.lang.String week)
   {
      this.week = week;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public int getTotalnoofBooking()
   {
      return this.totalnoofBooking;
   }

   public void setTotalnoofBooking(int totalnoofBooking)
   {
      this.totalnoofBooking = totalnoofBooking;
   }

   public java.util.Date getStartDate()
   {
      return this.startDate;
   }

   public void setStartDate(java.util.Date startDate)
   {
      this.startDate = startDate;
   }

   public java.util.Date getEndDate()
   {
      return this.endDate;
   }

   public void setEndDate(java.util.Date endDate)
   {
      this.endDate = endDate;
   }

   public int getPriceChange()
   {
      return this.priceChange;
   }

   public void setPriceChange(int priceChange)
   {
      this.priceChange = priceChange;
   }

   public java.lang.String getSchemeId()
   {
      return this.schemeId;
   }

   public void setSchemeId(java.lang.String schemeId)
   {
      this.schemeId = schemeId;
   }

   public Promotion(java.lang.String promotionName, java.lang.String products,
         java.lang.String week, java.lang.String type, int totalnoofBooking,
         java.util.Date startDate, java.util.Date endDate, int priceChange,
         java.lang.String schemeId)
   {
      this.promotionName = promotionName;
      this.products = products;
      this.week = week;
      this.type = type;
      this.totalnoofBooking = totalnoofBooking;
      this.startDate = startDate;
      this.endDate = endDate;
      this.priceChange = priceChange;
      this.schemeId = schemeId;
   }

}