package demo.discountcalculation;

import java.util.List;
import java.util.ArrayList;
/**
 * This class was automatically generated by the data modeler tool.
 */

public class DiscountRuleParameters implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String customerId;
   private java.lang.String inventoryId;

   private java.lang.String pcId;

   private java.lang.String projectName;

   private java.lang.String buildingId;

   private int bedroomType;

   private int numberofBedrooms;

   private java.lang.String facing;

   private int floor;

   private java.lang.String category;

   private java.lang.String subCategory;

   private float area;

   private int inventoryThreshold;

   private int customerThresoldValue;

   private java.lang.String productType;

   private double price;

   private java.lang.String residence;

   private java.lang.String region;

   private java.util.Date dateofBooking;

   private java.util.List<java.lang.String> unitId;

   private java.util.List<java.lang.Float> priceChange;

   private java.util.List<java.lang.Float> discountFlat;

   private java.util.List<java.lang.Float> discountPercent;

   private java.util.List<java.lang.String> gift;

   private java.util.List<java.lang.String> inLeu;

   public DiscountRuleParameters()
   {
   }

   public java.lang.String getCustomerId()
   {
      return this.customerId;
   }

   public void setCustomerId(java.lang.String customerId)
   {
      this.customerId = customerId;
   }

   public java.lang.String getInventoryId()
   {
      return this.inventoryId;
   }

   public void setInventoryId(java.lang.String inventoryId)
   {
      this.inventoryId = inventoryId;
   }

   public java.lang.String getPcId()
   {
      return this.pcId;
   }

   public void setPcId(java.lang.String pcId)
   {
      this.pcId = pcId;
   }

   public java.lang.String getProjectName()
   {
      return this.projectName;
   }

   public void setProjectName(java.lang.String projectName)
   {
      this.projectName = projectName;
   }

   public java.lang.String getBuildingId()
   {
      return this.buildingId;
   }

   public void setBuildingId(java.lang.String buildingId)
   {
      this.buildingId = buildingId;
   }

   public int getBedroomType()
   {
      return this.bedroomType;
   }

   public void setBedroomType(int bedroomType)
   {
      this.bedroomType = bedroomType;
   }

   public int getNumberofBedrooms()
   {
      return this.numberofBedrooms;
   }

   public void setNumberofBedrooms(int numberofBedrooms)
   {
      this.numberofBedrooms = numberofBedrooms;
   }

   public java.lang.String getFacing()
   {
      return this.facing;
   }

   public void setFacing(java.lang.String facing)
   {
      this.facing = facing;
   }

   public int getFloor()
   {
      return this.floor;
   }

   public void setFloor(int floor)
   {
      this.floor = floor;
   }

   public java.lang.String getCategory()
   {
      return this.category;
   }

   public void setCategory(java.lang.String category)
   {
      this.category = category;
   }

   public java.lang.String getSubCategory()
   {
      return this.subCategory;
   }

   public void setSubCategory(java.lang.String subCategory)
   {
      this.subCategory = subCategory;
   }

   public float getArea()
   {
      return this.area;
   }

   public void setArea(float area)
   {
      this.area = area;
   }

   public int getInventoryThreshold()
   {
      return this.inventoryThreshold;
   }

   public void setInventoryThreshold(int inventoryThreshold)
   {
      this.inventoryThreshold = inventoryThreshold;
   }

   public int getCustomerThresoldValue()
   {
      return this.customerThresoldValue;
   }

   public void setCustomerThresoldValue(int customerThresoldValue)
   {
      this.customerThresoldValue = customerThresoldValue;
   }

   public java.lang.String getProductType()
   {
      return this.productType;
   }

   public void setProductType(java.lang.String productType)
   {
      this.productType = productType;
   }

   public double getPrice()
   {
      return this.price;
   }

   public void setPrice(double price)
   {
      this.price = price;
   }

   public java.lang.String getResidence()
   {
      return this.residence;
   }

   public void setResidence(java.lang.String residence)
   {
      this.residence = residence;
   }

   public java.lang.String getRegion()
   {
      return this.region;
   }

   public void setRegion(java.lang.String region)
   {
      this.region = region;
   }

   public java.util.Date getDateofBooking()
   {
      return this.dateofBooking;
   }

   public void setDateofBooking(java.util.Date dateofBooking)
   {
      this.dateofBooking = dateofBooking;
   }

   public java.util.List<java.lang.String> getUnitId()
   {
      return this.unitId;
   }

   public void setUnitId(java.lang.String input)
   {
      List list = null;
		if (getUnitId() == null )
			list = new ArrayList<String>();
		else
			list =   getUnitId();
			
			list.add(input);
			unitId = list;
   }

   public java.util.List<java.lang.Float> getPriceChange()
   {
      return this.priceChange;
   }

   public void setPriceChange(java.lang.Float input)
   {
      List list = null;
		if (getPriceChange() == null )
			list = new ArrayList<Float>();
		else
			list =  getPriceChange();
			
			list.add(input);
			priceChange = list;
   }

   public java.util.List<java.lang.Float> getDiscountFlat()
   {
      return this.discountFlat;
   }

   public void setDiscountFlat(java.lang.Float input)
   {
      List list = null;
		if (getDiscountFlat() == null )
			list = new ArrayList<Float>();
		else
			list =  getDiscountFlat();
			
			list.add(input);
			discountFlat = list;
   }

   public java.util.List<java.lang.Float> getDiscountPercent()
   {
      return this.discountPercent;
   }

   public void setDiscountPercent(java.lang.Float input)
   {
      List list = null;
		if (getDiscountPercent() == null )
			list = new ArrayList<Float>();
		else
			list =  getDiscountPercent();
			
			list.add(input);
			discountPercent= list;
   }

   public java.util.List<java.lang.String> getGift()
   {
      return this.gift;
   }

   public void setGift(java.lang.String input)
   {
      List list = null;
		if (getGift() == null )
			list = new ArrayList<String>();
		else
			list = getGift();
			
			list.add(input);
			gift = list;
   }

   public java.util.List<java.lang.String> getInLeu()
   {
      return this.inLeu;
   }

   public void setInLeu(java.lang.String input)
   {
      List list = null;
		if (getInLeu() == null )
			list = new ArrayList<String>();
		else
			list = getInLeu();
			
			list.add(input);
			inLeu = list;
   }

   public DiscountRuleParameters(java.lang.String customerId,
         java.lang.String inventoryId, java.lang.String pcId,
         java.lang.String projectName, java.lang.String buildingId,
         int bedroomType, int numberofBedrooms, java.lang.String facing,
         int floor, java.lang.String category, java.lang.String subCategory,
         float area, int inventoryThreshold, int customerThresoldValue,
         java.lang.String productType, double price, java.lang.String residence,
         java.lang.String region, java.util.Date dateofBooking,
         java.util.List<java.lang.String> unitId,
         java.util.List<java.lang.Float> priceChange,
         java.util.List<java.lang.Float> discountFlat,
         java.util.List<java.lang.Float> discountPercent,
         java.util.List<java.lang.String> gift,
         java.util.List<java.lang.String> inLeu)
   {
      this.customerId = customerId;
      this.inventoryId = inventoryId;
      this.pcId = pcId;
      this.projectName = projectName;
      this.buildingId = buildingId;
      this.bedroomType = bedroomType;
      this.numberofBedrooms = numberofBedrooms;
      this.facing = facing;
      this.floor = floor;
      this.category = category;
      this.subCategory = subCategory;
      this.area = area;
      this.inventoryThreshold = inventoryThreshold;
      this.customerThresoldValue = customerThresoldValue;
      this.productType = productType;
      this.price = price;
      this.residence = residence;
      this.region = region;
      this.dateofBooking = dateofBooking;
      this.unitId = unitId;
      this.priceChange = priceChange;
      this.discountFlat = discountFlat;
      this.discountPercent = discountPercent;
      this.gift = gift;
      this.inLeu = inLeu;
   }

}