package demo.project1;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InOutObject implements java.io.Serializable
{

   static final long serialVersionUID = 1L;
   // input parameteres
   private java.lang.String pcId;
   private java.lang.String customerId;
   private java.lang.String inventoryId;
   private java.lang.String projectName;
   private int bedroomType;
   private int numberofBedrooms;
   private java.lang.String facing;
   private int floor;
   private java.lang.String category;
   private java.lang.String subCategory;
   private float area;
   private int inventoryThreshold;
   private int customerthresholdValue;
   private java.lang.String productType;
   private float price;
   private java.lang.String residence;
   private java.lang.String region;
   private Date dateofBooking;
   // output parameters for Scheme Name
   private float priceChangePSF;
   private float discountFlatSN;
   private float discountPercentSN;
   private java.lang.String giftSN;
   private java.lang.String inLeuSN;
   //promotion name
   private java.lang.String unitIdPN;
   private float priceChangePN;
   private float discountFlatPN;
   private float discountPercentPN;

   private java.lang.String giftPN;
   private java.lang.String inLeuPN;
   //campaign
   private java.lang.String unitIdCN;
   private java.lang.String giftCN;
   private float discountPercentCN;
   private float discountFlatCN;
   //payment plan
   private java.lang.String unitIdPP;
   private java.lang.String paymentAtMilestone;
   private float priceChangePer;

   private java.lang.String buildingName;
   private java.lang.String marketingProject;
   private java.lang.String views;
   private java.lang.String cunstructionStatus;
   private java.lang.String agent;
   //option perameters
   private java.lang.String option1Id;
   private java.lang.String option1Name;
   private float option1Price;

   private java.lang.String option2Id;
   private java.lang.String option2Name;
   private float option2Price;
   private java.lang.String option3Id;
   private java.lang.String option3Name;
   private float option3Price;
   private java.lang.String option4Id;
   private java.lang.String option4Name;
   private float option4Price;
   private java.lang.String option5Id;
   private java.lang.String option5Name;
   private float option5Price;
   private java.lang.String option6Id;
   private java.lang.String option6Name;
   private float option6Price;

   private float discountPSF_CN;
   private java.lang.String promoNameSN;
   private java.lang.String promoNamePN;
   private java.lang.String waiverPN;
   private float discountPSF_PN;
   private float discountPSF_SN;

   private java.lang.String waiverIdPN;
   private java.lang.String waiverIdCN;
   private java.lang.String templateIdCN;
   private java.lang.String waiverCN;

   private java.lang.String templateIdPN;

   private java.lang.String waiveridSN;
   private java.lang.String waiverSN;
   private java.lang.String templateIdSN;

   private int noofUnits;
   private double totalArea;
   private double totalDealValue;

   private java.lang.String inLeuCN;

   public InOutObject()
   {
   }

   public java.lang.String getPcId()
   {
      return this.pcId;
   }

   public void setPcId(java.lang.String pcId)
   {
      this.pcId = pcId;
   }

   public java.lang.String getCustomerId()
   {
      return this.customerId;
   }

   public void setCustomerId(java.lang.String customerId)
   {
      this.customerId = customerId;
   }

   public java.lang.String getInventoryId()
   {
      return this.inventoryId;
   }

   public void setInventoryId(java.lang.String inventoryId)
   {
      this.inventoryId = inventoryId;
   }

   public java.lang.String getProjectName()
   {
      return this.projectName;
   }

   public void setProjectName(java.lang.String projectName)
   {
      this.projectName = projectName;
   }

   public int getBedroomType()
   {
      return this.bedroomType;
   }

   public void setBedroomType(int bedroomType)
   {
      this.bedroomType = bedroomType;
   }

   public int getNumberofBedrooms()
   {
      return this.numberofBedrooms;
   }

   public void setNumberofBedrooms(int numberofBedrooms)
   {
      this.numberofBedrooms = numberofBedrooms;
   }

   public java.lang.String getFacing()
   {
      return this.facing;
   }

   public void setFacing(java.lang.String facing)
   {
      this.facing = facing;
   }

   public int getFloor()
   {
      return this.floor;
   }

   public void setFloor(int floor)
   {
      this.floor = floor;
   }

   public java.lang.String getCategory()
   {
      return this.category;
   }

   public void setCategory(java.lang.String category)
   {
      this.category = category;
   }

   public java.lang.String getSubCategory()
   {
      return this.subCategory;
   }

   public void setSubCategory(java.lang.String subCategory)
   {
      this.subCategory = subCategory;
   }

   public float getArea()
   {
      return this.area;
   }

   public void setArea(float area)
   {
      this.area = area;
   }

   public int getInventoryThreshold()
   {
      return this.inventoryThreshold;
   }

   public void setInventoryThreshold(int inventoryThreshold)
   {
      this.inventoryThreshold = inventoryThreshold;
   }

   public int getCustomerthresholdValue()
   {
      return this.customerthresholdValue;
   }

   public void setCustomerthresholdValue(int customerthresholdValue)
   {
      this.customerthresholdValue = customerthresholdValue;
   }

   public java.lang.String getProductType()
   {
      return this.productType;
   }

   public void setProductType(java.lang.String productType)
   {
      this.productType = productType;
   }

   public float getPrice()
   {
      return this.price;
   }

   public void setPrice(float price)
   {
      this.price = price;
   }

   public java.lang.String getResidence()
   {
      return this.residence;
   }

   public void setResidence(java.lang.String residence)
   {
      this.residence = residence;
   }

   public java.lang.String getRegion()
   {
      return this.region;
   }

   public void setRegion(java.lang.String region)
   {
      this.region = region;
   }

   public float getPriceChangePSF()
   {
      return this.priceChangePSF;
   }

   public void setPriceChangePSF(float priceChangePSF)
   {
      this.priceChangePSF = priceChangePSF;
   }

   public float getDiscountFlatSN()
   {
      return this.discountFlatSN;
   }

   public void setDiscountFlatSN(float discountFlatSN)
   {
      this.discountFlatSN = discountFlatSN;
   }

   public float getDiscountPercentSN()
   {
      return this.discountPercentSN;
   }

   public void setDiscountPercentSN(float discountPercentSN)
   {
      this.discountPercentSN = discountPercentSN;
   }

   public java.lang.String getGiftSN()
   {
      return this.giftSN;
   }

   public void setGiftSN(java.lang.String giftSN)
   {
      this.giftSN = giftSN;
   }

   public java.lang.String getInLeuSN()
   {
      return this.inLeuSN;
   }

   public void setInLeuSN(java.lang.String inLeuSN)
   {
      this.inLeuSN = inLeuSN;
   }

   public java.lang.String getUnitIdPN()
   {
      return this.unitIdPN;
   }

   public void setUnitIdPN(java.lang.String unitIdPN)
   {
      this.unitIdPN = unitIdPN;
   }

   public float getPriceChangePN()
   {
      return this.priceChangePN;
   }

   public void setPriceChangePN(float priceChangePN)
   {
      this.priceChangePN = priceChangePN;
   }

   public float getDiscountFlatPN()
   {
      return this.discountFlatPN;
   }

   public void setDiscountFlatPN(float discountFlatPN)
   {
      this.discountFlatPN = discountFlatPN;
   }

   public float getDiscountPercentCN()
   {
      return this.discountPercentCN;
   }

   public void setDiscountPercentCN(float discountPercentCN)
   {
      this.discountPercentCN = discountPercentCN;
   }

   public java.lang.String getGiftPN()
   {
      return this.giftPN;
   }

   public void setGiftPN(java.lang.String giftPN)
   {
      this.giftPN = giftPN;
   }

   public java.lang.String getInLeuPN()
   {
      return this.inLeuPN;
   }

   public void setInLeuPN(java.lang.String inLeuPN)
   {
      this.inLeuPN = inLeuPN;
   }

   public java.lang.String getUnitIdCN()
   {
      return this.unitIdCN;
   }

   public void setUnitIdCN(java.lang.String unitIdCN)
   {
      this.unitIdCN = unitIdCN;
   }

   public java.lang.String getGiftCN()
   {
      return this.giftCN;
   }

   public void setGiftCN(java.lang.String giftCN)
   {
      this.giftCN = giftCN;
   }

   public float getDiscountFlatCN()
   {
      return this.discountFlatCN;
   }

   public void setDiscountFlatCN(float discountFlatCN)
   {
      this.discountFlatCN = discountFlatCN;
   }

   public java.lang.String getUnitIdPP()
   {
      return this.unitIdPP;
   }

   public void setUnitIdPP(java.lang.String unitIdPP)
   {
      this.unitIdPP = unitIdPP;
   }

   public java.lang.String getPaymentAtMilestone()
   {
      return this.paymentAtMilestone;
   }

   public void setPaymentAtMilestone(java.lang.String paymentAtMilestone)
   {
      this.paymentAtMilestone = paymentAtMilestone;
   }

   public float getPriceChangePer()
   {
      return this.priceChangePer;
   }

   public void setPriceChangePer(float priceChangePer)
   {
      this.priceChangePer = priceChangePer;
   }

   public float getDiscountPercentPN()
   {
      return this.discountPercentPN;
   }

   public void setDiscountPercentPN(float discountPercentPN)
   {
      this.discountPercentPN = discountPercentPN;
   }

   public java.lang.String getBuildingName()
   {
      return this.buildingName;
   }

   public void setBuildingName(java.lang.String buildingName)
   {
      this.buildingName = buildingName;
   }

   public java.util.Date getDateofBooking()
   {
      return this.dateofBooking;
   }

   public void setDateofBooking(java.util.Date dateofBooking)
   {
      this.dateofBooking = dateofBooking;
   }

   public java.lang.String getMarketingProject()
   {
      return this.marketingProject;
   }

   public void setMarketingProject(java.lang.String marketingProject)
   {
      this.marketingProject = marketingProject;
   }

   public java.lang.String getViews()
   {
      return this.views;
   }

   public void setViews(java.lang.String views)
   {
      this.views = views;
   }

   public java.lang.String getCunstructionStatus()
   {
      return this.cunstructionStatus;
   }

   public void setCunstructionStatus(java.lang.String cunstructionStatus)
   {
      this.cunstructionStatus = cunstructionStatus;
   }

   public java.lang.String getAgent()
   {
      return this.agent;
   }

   public void setAgent(java.lang.String agent)
   {
      this.agent = agent;
   }

   public java.lang.String getOption1Id()
   {
      return this.option1Id;
   }

   public void setOption1Id(java.lang.String option1Id)
   {
      this.option1Id = option1Id;
   }

   public java.lang.String getOption1Name()
   {
      return this.option1Name;
   }

   public void setOption1Name(java.lang.String option1Name)
   {
      this.option1Name = option1Name;
   }

   public float getOption1Price()
   {
      return this.option1Price;
   }

   public void setOption1Price(float option1Price)
   {
      this.option1Price = option1Price;
   }

   public java.lang.String getOption2Id()
   {
      return this.option2Id;
   }

   public void setOption2Id(java.lang.String option2Id)
   {
      this.option2Id = option2Id;
   }

   public java.lang.String getOption2Name()
   {
      return this.option2Name;
   }

   public void setOption2Name(java.lang.String option2Name)
   {
      this.option2Name = option2Name;
   }

   public float getOption2Price()
   {
      return this.option2Price;
   }

   public void setOption2Price(float option2Price)
   {
      this.option2Price = option2Price;
   }

   public java.lang.String getOption3Id()
   {
      return this.option3Id;
   }

   public void setOption3Id(java.lang.String option3Id)
   {
      this.option3Id = option3Id;
   }

   public java.lang.String getOption3Name()
   {
      return this.option3Name;
   }

   public void setOption3Name(java.lang.String option3Name)
   {
      this.option3Name = option3Name;
   }

   public float getOption3Price()
   {
      return this.option3Price;
   }

   public void setOption3Price(float option3Price)
   {
      this.option3Price = option3Price;
   }

   public java.lang.String getOption4Id()
   {
      return this.option4Id;
   }

   public void setOption4Id(java.lang.String option4Id)
   {
      this.option4Id = option4Id;
   }

   public java.lang.String getOption4Name()
   {
      return this.option4Name;
   }

   public void setOption4Name(java.lang.String option4Name)
   {
      this.option4Name = option4Name;
   }

   public float getOption4Price()
   {
      return this.option4Price;
   }

   public void setOption4Price(float option4Price)
   {
      this.option4Price = option4Price;
   }

   public java.lang.String getOption5Id()
   {
      return this.option5Id;
   }

   public void setOption5Id(java.lang.String option5Id)
   {
      this.option5Id = option5Id;
   }

   public java.lang.String getOption5Name()
   {
      return this.option5Name;
   }

   public void setOption5Name(java.lang.String option5Name)
   {
      this.option5Name = option5Name;
   }

   public float getOption5Price()
   {
      return this.option5Price;
   }

   public void setOption5Price(float option5Price)
   {
      this.option5Price = option5Price;
   }

   public java.lang.String getOption6Id()
   {
      return this.option6Id;
   }

   public void setOption6Id(java.lang.String option6Id)
   {
      this.option6Id = option6Id;
   }

   public java.lang.String getOption6Name()
   {
      return this.option6Name;
   }

   public void setOption6Name(java.lang.String option6Name)
   {
      this.option6Name = option6Name;
   }

   public float getOption6Price()
   {
      return this.option6Price;
   }

   public void setOption6Price(float option6Price)
   {
      this.option6Price = option6Price;
   }

   public float getDiscountPSF_CN()
   {
      return this.discountPSF_CN;
   }

   public void setDiscountPSF_CN(float discountPSF_CN)
   {
      this.discountPSF_CN = discountPSF_CN;
   }

   public java.lang.String getPromoNameSN()
   {
      return this.promoNameSN;
   }

   public void setPromoNameSN(java.lang.String promoNameSN)
   {
      this.promoNameSN = promoNameSN;
   }

   public java.lang.String getPromoNamePN()
   {
      return this.promoNamePN;
   }

   public void setPromoNamePN(java.lang.String promoNamePN)
   {
      this.promoNamePN = promoNamePN;
   }

   public java.lang.String getWaiverPN()
   {
      return this.waiverPN;
   }

   public void setWaiverPN(java.lang.String waiverPN)
   {
      this.waiverPN = waiverPN;
   }

   public float getDiscountPSF_PN()
   {
      return this.discountPSF_PN;
   }

   public void setDiscountPSF_PN(float discountPSF_PN)
   {
      this.discountPSF_PN = discountPSF_PN;
   }

   public float getDiscountPSF_SN()
   {
      return this.discountPSF_SN;
   }

   public void setDiscountPSF_SN(float discountPSF_SN)
   {
      this.discountPSF_SN = discountPSF_SN;
   }

   public java.lang.String getWaiverIdPN()
   {
      return this.waiverIdPN;
   }

   public void setWaiverIdPN(java.lang.String waiverIdPN)
   {
      this.waiverIdPN = waiverIdPN;
   }

   public java.lang.String getWaiverIdCN()
   {
      return this.waiverIdCN;
   }

   public void setWaiverIdCN(java.lang.String waiverIdCN)
   {
      this.waiverIdCN = waiverIdCN;
   }

   public java.lang.String getTemplateIdCN()
   {
      return this.templateIdCN;
   }

   public void setTemplateIdCN(java.lang.String templateIdCN)
   {
      this.templateIdCN = templateIdCN;
   }

   public java.lang.String getWaiverCN()
   {
      return this.waiverCN;
   }

   public void setWaiverCN(java.lang.String waiverCN)
   {
      this.waiverCN = waiverCN;
   }

   public java.lang.String getTemplateIdPN()
   {
      return this.templateIdPN;
   }

   public void setTemplateIdPN(java.lang.String templateIdPN)
   {
      this.templateIdPN = templateIdPN;
   }

   public java.lang.String getWaiveridSN()
   {
      return this.waiveridSN;
   }

   public void setWaiveridSN(java.lang.String waiveridSN)
   {
      this.waiveridSN = waiveridSN;
   }

   public java.lang.String getWaiverSN()
   {
      return this.waiverSN;
   }

   public void setWaiverSN(java.lang.String waiverSN)
   {
      this.waiverSN = waiverSN;
   }

   public java.lang.String getTemplateIdSN()
   {
      return this.templateIdSN;
   }

   public void setTemplateIdSN(java.lang.String templateIdSN)
   {
      this.templateIdSN = templateIdSN;
   }

   public int getNoofUnits()
   {
      return this.noofUnits;
   }

   public void setNoofUnits(int noofUnits)
   {
      this.noofUnits = noofUnits;
   }

   public double getTotalArea()
   {
      return this.totalArea;
   }

   public void setTotalArea(double totalArea)
   {
      this.totalArea = totalArea;
   }

   public double getTotalDealValue()
   {
      return this.totalDealValue;
   }

   public void setTotalDealValue(double totalDealValue)
   {
      this.totalDealValue = totalDealValue;
   }

   public java.lang.String getInLeuCN()
   {
      return this.inLeuCN;
   }

   public void setInLeuCN(java.lang.String inLeuCN)
   {
      this.inLeuCN = inLeuCN;
   }

   public InOutObject(java.lang.String pcId, java.lang.String customerId,
         java.lang.String inventoryId, java.lang.String projectName,
         int bedroomType, int numberofBedrooms, java.lang.String facing,
         int floor, java.lang.String category, java.lang.String subCategory,
         float area, int inventoryThreshold, int customerthresholdValue,
         java.lang.String productType, float price, java.lang.String residence,
         java.lang.String region, java.util.Date dateofBooking,
         float priceChangePSF, float discountFlatSN, float discountPercentSN,
         java.lang.String giftSN, java.lang.String inLeuSN,
         java.lang.String unitIdPN, float priceChangePN, float discountFlatPN,
         float discountPercentPN, java.lang.String giftPN,
         java.lang.String inLeuPN, java.lang.String unitIdCN,
         java.lang.String giftCN, float discountPercentCN, float discountFlatCN,
         java.lang.String unitIdPP, java.lang.String paymentAtMilestone,
         float priceChangePer, java.lang.String buildingName,
         java.lang.String marketingProject, java.lang.String views,
         java.lang.String cunstructionStatus, java.lang.String agent,
         java.lang.String option1Id, java.lang.String option1Name,
         float option1Price, java.lang.String option2Id,
         java.lang.String option2Name, float option2Price,
         java.lang.String option3Id, java.lang.String option3Name,
         float option3Price, java.lang.String option4Id,
         java.lang.String option4Name, float option4Price,
         java.lang.String option5Id, java.lang.String option5Name,
         float option5Price, java.lang.String option6Id,
         java.lang.String option6Name, float option6Price, float discountPSF_CN,
         java.lang.String promoNameSN, java.lang.String promoNamePN,
         java.lang.String waiverPN, float discountPSF_PN, float discountPSF_SN,
         java.lang.String waiverIdPN, java.lang.String waiverIdCN,
         java.lang.String templateIdCN, java.lang.String waiverCN,
         java.lang.String templateIdPN, java.lang.String waiveridSN,
         java.lang.String waiverSN, java.lang.String templateIdSN,
         int noofUnits, double totalArea, double totalDealValue,
         java.lang.String inLeuCN)
   {
      this.pcId = pcId;
      this.customerId = customerId;
      this.inventoryId = inventoryId;
      this.projectName = projectName;
      this.bedroomType = bedroomType;
      this.numberofBedrooms = numberofBedrooms;
      this.facing = facing;
      this.floor = floor;
      this.category = category;
      this.subCategory = subCategory;
      this.area = area;
      this.inventoryThreshold = inventoryThreshold;
      this.customerthresholdValue = customerthresholdValue;
      this.productType = productType;
      this.price = price;
      this.residence = residence;
      this.region = region;
      this.dateofBooking = dateofBooking;
      this.priceChangePSF = priceChangePSF;
      this.discountFlatSN = discountFlatSN;
      this.discountPercentSN = discountPercentSN;
      this.giftSN = giftSN;
      this.inLeuSN = inLeuSN;
      this.unitIdPN = unitIdPN;
      this.priceChangePN = priceChangePN;
      this.discountFlatPN = discountFlatPN;
      this.discountPercentPN = discountPercentPN;
      this.giftPN = giftPN;
      this.inLeuPN = inLeuPN;
      this.unitIdCN = unitIdCN;
      this.giftCN = giftCN;
      this.discountPercentCN = discountPercentCN;
      this.discountFlatCN = discountFlatCN;
      this.unitIdPP = unitIdPP;
      this.paymentAtMilestone = paymentAtMilestone;
      this.priceChangePer = priceChangePer;
      this.buildingName = buildingName;
      this.marketingProject = marketingProject;
      this.views = views;
      this.cunstructionStatus = cunstructionStatus;
      this.agent = agent;
      this.option1Id = option1Id;
      this.option1Name = option1Name;
      this.option1Price = option1Price;
      this.option2Id = option2Id;
      this.option2Name = option2Name;
      this.option2Price = option2Price;
      this.option3Id = option3Id;
      this.option3Name = option3Name;
      this.option3Price = option3Price;
      this.option4Id = option4Id;
      this.option4Name = option4Name;
      this.option4Price = option4Price;
      this.option5Id = option5Id;
      this.option5Name = option5Name;
      this.option5Price = option5Price;
      this.option6Id = option6Id;
      this.option6Name = option6Name;
      this.option6Price = option6Price;
      this.discountPSF_CN = discountPSF_CN;
      this.promoNameSN = promoNameSN;
      this.promoNamePN = promoNamePN;
      this.waiverPN = waiverPN;
      this.discountPSF_PN = discountPSF_PN;
      this.discountPSF_SN = discountPSF_SN;
      this.waiverIdPN = waiverIdPN;
      this.waiverIdCN = waiverIdCN;
      this.templateIdCN = templateIdCN;
      this.waiverCN = waiverCN;
      this.templateIdPN = templateIdPN;
      this.waiveridSN = waiveridSN;
      this.waiverSN = waiverSN;
      this.templateIdSN = templateIdSN;
      this.noofUnits = noofUnits;
      this.totalArea = totalArea;
      this.totalDealValue = totalDealValue;
      this.inLeuCN = inLeuCN;
   }

}